apiVersion: v1
kind: Service
metadata:
  name: message-dispatch
  labels:
    app: message-dispatch
spec:
  type: ClusterIP
  selector:
    app: message-dispatch
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
    - protocol: TCP
      port: 8080
      targetPort: 8080