apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lagrange-onebot-pvc
  labels:
    app: lagrange-onebot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # 根据需要调整存储大小
  # 如果使用特定的存储类，取消注释下面的行
  # storageClassName: your-storage-class