apiVersion: v1
kind: Service
metadata:
  name: lagrange-onebot-service
  labels:
    app: lagrange-onebot
spec:
  type: ClusterIP 
  ports:
  - port: 15000
    targetPort: 15000
    protocol: TCP
    name: http
  selector:
    app: lagrange-onebot